


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."es_admin"() RETURNS boolean
    LANGUAGE "sql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
  select exists (
    select 1
    from perfiles
    where id = auth.uid()
      and rol = 'ADMIN'
  );
$$;


ALTER FUNCTION "public"."es_admin"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."registrar_log"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $_$
DECLARE
    pk_column text;
    registro_id text;
BEGIN
    -- Obtener el nombre de la primary key dinámicamente
    SELECT a.attname
    INTO pk_column
    FROM pg_index i
    JOIN pg_attribute a 
        ON a.attrelid = i.indrelid
        AND a.attnum = ANY(i.indkey)
    WHERE i.indrelid = TG_RELID
    AND i.indisprimary
    LIMIT 1;

    -- Obtener el valor del ID dinámicamente
    IF TG_OP = 'DELETE' THEN
        EXECUTE format('SELECT ($1).%I::text', pk_column)
        INTO registro_id
        USING OLD;
    ELSE
        EXECUTE format('SELECT ($1).%I::text', pk_column)
        INTO registro_id
        USING NEW;
    END IF;

    -- Insertar en log
    INSERT INTO log (
        user_id,
        tabla_afectada,
        accion,
        registro_id,
        datos_anteriores,
        datos_nuevos
    )
    VALUES (
        auth.uid(),
        TG_TABLE_NAME,
        TG_OP,
        registro_id,
        to_jsonb(OLD),
        to_jsonb(NEW)
    );

    RETURN COALESCE(NEW, OLD);
END;
$_$;


ALTER FUNCTION "public"."registrar_log"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."colaboradores" (
    "id_colab" bigint NOT NULL,
    "nombre_colab" "text",
    "asignacion_act" "text",
    "supervisor_act_id" bigint,
    "supervisor_reg_id" bigint,
    "dep_id" character varying(10),
    "puesto_id" bigint,
    "is_active" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."colaboradores" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."curso_grupo" (
    "id_grupo" smallint NOT NULL,
    "grupo_nombre" character varying
);


ALTER TABLE "public"."curso_grupo" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."cursos" (
    "id_curso" character varying(7) NOT NULL,
    "nombre_curso" "text",
    "primera_fecha" "date",
    "ultima_fecha" "date",
    "estado" "text",
    "grupo_curso" integer,
    "origen" "text",
    "is_active" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."cursos" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."dep_puesto_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."dep_puesto_id_seq" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."departamento" (
    "id_dep" character varying(10) NOT NULL,
    "nombre_dep" character varying(25),
    "is_active" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."departamento" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."departamento_puesto" (
    "id_dep_puesto" integer NOT NULL,
    "puesto_id" integer,
    "dep_id" character varying,
    "colab_id" integer
);


ALTER TABLE "public"."departamento_puesto" OWNER TO "postgres";


ALTER TABLE "public"."departamento_puesto" ALTER COLUMN "id_dep_puesto" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."departamento_puesto_id_dep_puesto_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."historial_cursos" (
    "id_historial" bigint NOT NULL,
    "fecha_inicio" "date" NOT NULL,
    "fecha_final" "date",
    "estado" "text",
    "duracion_horas" real,
    "colaborador_id" bigint NOT NULL,
    "curso_id" character varying NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."historial_cursos" OWNER TO "postgres";


ALTER TABLE "public"."historial_cursos" ALTER COLUMN "id_historial" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."historial_cursos_id_historial_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."log" (
    "id_log" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "tabla_afectada" "text" NOT NULL,
    "accion" "text" NOT NULL,
    "registro_id" "text" NOT NULL,
    "datos_anteriores" "jsonb",
    "datos_nuevos" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."log" OWNER TO "postgres";


ALTER TABLE "public"."log" ALTER COLUMN "id_log" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."log_id_log_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."perfiles" (
    "id" "uuid" NOT NULL,
    "nombre" "text",
    "rol" "text" DEFAULT 'SUPERVISOR'::"text" NOT NULL,
    "creado_en" timestamp without time zone DEFAULT "now"(),
    "is_active" boolean DEFAULT true NOT NULL,
    CONSTRAINT "perfiles_rol_check" CHECK (("rol" = ANY (ARRAY['ADMIN'::"text", 'SUPERVISOR'::"text"])))
);


ALTER TABLE "public"."perfiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."puesto_curso" (
    "id_puesto_curso" smallint NOT NULL,
    "clasificacion_estrategica" character varying(11),
    "vigencia_anio" smallint,
    "estado" character varying(20),
    "curso_id" character varying(7),
    "puesto_id" integer
);


ALTER TABLE "public"."puesto_curso" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."puestos" (
    "id_puesto" integer NOT NULL,
    "nombre_puesto" "text",
    "is_active" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."puestos" OWNER TO "postgres";


ALTER TABLE "public"."puestos" ALTER COLUMN "id_puesto" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."puestos_id_puesto_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."colaboradores"
    ADD CONSTRAINT "colaboradores_pkey" PRIMARY KEY ("id_colab");



ALTER TABLE ONLY "public"."curso_grupo"
    ADD CONSTRAINT "curso_grupo_pkey" PRIMARY KEY ("id_grupo");



ALTER TABLE ONLY "public"."cursos"
    ADD CONSTRAINT "cursos_pkey" PRIMARY KEY ("id_curso");



ALTER TABLE ONLY "public"."departamento"
    ADD CONSTRAINT "departamento_pkey" PRIMARY KEY ("id_dep");



ALTER TABLE ONLY "public"."departamento_puesto"
    ADD CONSTRAINT "departamento_puesto_pkey" PRIMARY KEY ("id_dep_puesto");



ALTER TABLE ONLY "public"."departamento_puesto"
    ADD CONSTRAINT "departamento_puesto_unique" UNIQUE ("puesto_id", "dep_id", "colab_id");



ALTER TABLE ONLY "public"."historial_cursos"
    ADD CONSTRAINT "historial_cursos_id_historial_key" UNIQUE ("id_historial");



ALTER TABLE ONLY "public"."historial_cursos"
    ADD CONSTRAINT "historial_cursos_pkey" PRIMARY KEY ("id_historial");



ALTER TABLE ONLY "public"."log"
    ADD CONSTRAINT "log_pkey" PRIMARY KEY ("id_log");



ALTER TABLE ONLY "public"."perfiles"
    ADD CONSTRAINT "perfiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."puesto_curso"
    ADD CONSTRAINT "puesto_curso_pkey" PRIMARY KEY ("id_puesto_curso");



ALTER TABLE ONLY "public"."puestos"
    ADD CONSTRAINT "puestos_pkey" PRIMARY KEY ("id_puesto");



CREATE OR REPLACE TRIGGER "trigger_log_colaboradores" AFTER INSERT OR DELETE OR UPDATE ON "public"."colaboradores" FOR EACH ROW EXECUTE FUNCTION "public"."registrar_log"();



CREATE OR REPLACE TRIGGER "trigger_log_curso_grupo" AFTER INSERT OR DELETE OR UPDATE ON "public"."curso_grupo" FOR EACH ROW EXECUTE FUNCTION "public"."registrar_log"();



CREATE OR REPLACE TRIGGER "trigger_log_cursos" AFTER INSERT OR DELETE OR UPDATE ON "public"."cursos" FOR EACH ROW EXECUTE FUNCTION "public"."registrar_log"();



CREATE OR REPLACE TRIGGER "trigger_log_departamento" AFTER INSERT OR DELETE OR UPDATE ON "public"."departamento" FOR EACH ROW EXECUTE FUNCTION "public"."registrar_log"();



CREATE OR REPLACE TRIGGER "trigger_log_departamento_puesto" AFTER INSERT OR DELETE OR UPDATE ON "public"."departamento_puesto" FOR EACH ROW EXECUTE FUNCTION "public"."registrar_log"();



CREATE OR REPLACE TRIGGER "trigger_log_historial_cursos" AFTER INSERT OR DELETE OR UPDATE ON "public"."historial_cursos" FOR EACH ROW EXECUTE FUNCTION "public"."registrar_log"();



CREATE OR REPLACE TRIGGER "trigger_log_perfiles" AFTER INSERT OR DELETE OR UPDATE ON "public"."perfiles" FOR EACH ROW EXECUTE FUNCTION "public"."registrar_log"();



CREATE OR REPLACE TRIGGER "trigger_log_puesto_curso" AFTER INSERT OR DELETE OR UPDATE ON "public"."puesto_curso" FOR EACH ROW EXECUTE FUNCTION "public"."registrar_log"();



CREATE OR REPLACE TRIGGER "trigger_log_puestos" AFTER INSERT OR DELETE OR UPDATE ON "public"."puestos" FOR EACH ROW EXECUTE FUNCTION "public"."registrar_log"();



ALTER TABLE ONLY "public"."departamento_puesto"
    ADD CONSTRAINT "fk_colab_id" FOREIGN KEY ("colab_id") REFERENCES "public"."colaboradores"("id_colab");



ALTER TABLE ONLY "public"."puesto_curso"
    ADD CONSTRAINT "fk_curso_id_pc" FOREIGN KEY ("curso_id") REFERENCES "public"."cursos"("id_curso");



ALTER TABLE ONLY "public"."colaboradores"
    ADD CONSTRAINT "fk_dep_id" FOREIGN KEY ("dep_id") REFERENCES "public"."departamento"("id_dep");



ALTER TABLE ONLY "public"."departamento_puesto"
    ADD CONSTRAINT "fk_dep_id" FOREIGN KEY ("dep_id") REFERENCES "public"."departamento"("id_dep");



ALTER TABLE ONLY "public"."cursos"
    ADD CONSTRAINT "fk_grupo_curso" FOREIGN KEY ("grupo_curso") REFERENCES "public"."curso_grupo"("id_grupo");



ALTER TABLE ONLY "public"."log"
    ADD CONSTRAINT "fk_log_perfiles" FOREIGN KEY ("user_id") REFERENCES "public"."perfiles"("id");



ALTER TABLE ONLY "public"."colaboradores"
    ADD CONSTRAINT "fk_puesto_id" FOREIGN KEY ("puesto_id") REFERENCES "public"."puestos"("id_puesto");



ALTER TABLE ONLY "public"."departamento_puesto"
    ADD CONSTRAINT "fk_puesto_id" FOREIGN KEY ("puesto_id") REFERENCES "public"."puestos"("id_puesto");



ALTER TABLE ONLY "public"."puesto_curso"
    ADD CONSTRAINT "fk_puesto_id_pc" FOREIGN KEY ("puesto_id") REFERENCES "public"."puestos"("id_puesto");



ALTER TABLE ONLY "public"."colaboradores"
    ADD CONSTRAINT "fk_sup_act" FOREIGN KEY ("supervisor_act_id") REFERENCES "public"."colaboradores"("id_colab");



ALTER TABLE ONLY "public"."colaboradores"
    ADD CONSTRAINT "fk_sup_reg" FOREIGN KEY ("supervisor_reg_id") REFERENCES "public"."colaboradores"("id_colab");



ALTER TABLE ONLY "public"."historial_cursos"
    ADD CONSTRAINT "historial_cursos_colaborador_id_fkey" FOREIGN KEY ("colaborador_id") REFERENCES "public"."colaboradores"("id_colab") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."historial_cursos"
    ADD CONSTRAINT "historial_cursos_curso_id_fkey" FOREIGN KEY ("curso_id") REFERENCES "public"."cursos"("id_curso") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."log"
    ADD CONSTRAINT "log_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."perfiles"
    ADD CONSTRAINT "perfiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Admin puede ver todos los perfiles" ON "public"."perfiles" FOR SELECT USING (("public"."es_admin"() OR ("id" = "auth"."uid"())));



CREATE POLICY "Ver propio perfil" ON "public"."perfiles" FOR SELECT USING (("auth"."uid"() = "id"));



CREATE POLICY "allow read log" ON "public"."log" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "allow read perfiles" ON "public"."perfiles" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."log" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."perfiles" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."es_admin"() TO "anon";
GRANT ALL ON FUNCTION "public"."es_admin"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."es_admin"() TO "service_role";



GRANT ALL ON FUNCTION "public"."registrar_log"() TO "anon";
GRANT ALL ON FUNCTION "public"."registrar_log"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."registrar_log"() TO "service_role";


















GRANT ALL ON TABLE "public"."colaboradores" TO "anon";
GRANT ALL ON TABLE "public"."colaboradores" TO "authenticated";
GRANT ALL ON TABLE "public"."colaboradores" TO "service_role";



GRANT ALL ON TABLE "public"."curso_grupo" TO "anon";
GRANT ALL ON TABLE "public"."curso_grupo" TO "authenticated";
GRANT ALL ON TABLE "public"."curso_grupo" TO "service_role";



GRANT ALL ON TABLE "public"."cursos" TO "anon";
GRANT ALL ON TABLE "public"."cursos" TO "authenticated";
GRANT ALL ON TABLE "public"."cursos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."dep_puesto_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."dep_puesto_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."dep_puesto_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."departamento" TO "anon";
GRANT ALL ON TABLE "public"."departamento" TO "authenticated";
GRANT ALL ON TABLE "public"."departamento" TO "service_role";



GRANT ALL ON TABLE "public"."departamento_puesto" TO "anon";
GRANT ALL ON TABLE "public"."departamento_puesto" TO "authenticated";
GRANT ALL ON TABLE "public"."departamento_puesto" TO "service_role";



GRANT ALL ON SEQUENCE "public"."departamento_puesto_id_dep_puesto_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."departamento_puesto_id_dep_puesto_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."departamento_puesto_id_dep_puesto_seq" TO "service_role";



GRANT ALL ON TABLE "public"."historial_cursos" TO "anon";
GRANT ALL ON TABLE "public"."historial_cursos" TO "authenticated";
GRANT ALL ON TABLE "public"."historial_cursos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."historial_cursos_id_historial_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."historial_cursos_id_historial_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."historial_cursos_id_historial_seq" TO "service_role";



GRANT ALL ON TABLE "public"."log" TO "anon";
GRANT ALL ON TABLE "public"."log" TO "authenticated";
GRANT ALL ON TABLE "public"."log" TO "service_role";



GRANT ALL ON SEQUENCE "public"."log_id_log_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."log_id_log_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."log_id_log_seq" TO "service_role";



GRANT ALL ON TABLE "public"."perfiles" TO "anon";
GRANT ALL ON TABLE "public"."perfiles" TO "authenticated";
GRANT ALL ON TABLE "public"."perfiles" TO "service_role";



GRANT ALL ON TABLE "public"."puesto_curso" TO "anon";
GRANT ALL ON TABLE "public"."puesto_curso" TO "authenticated";
GRANT ALL ON TABLE "public"."puesto_curso" TO "service_role";



GRANT ALL ON TABLE "public"."puestos" TO "anon";
GRANT ALL ON TABLE "public"."puestos" TO "authenticated";
GRANT ALL ON TABLE "public"."puestos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."puestos_id_puesto_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."puestos_id_puesto_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."puestos_id_puesto_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































